language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install codecov
# command to run tests
script: nosetests --with-coverage
